"""
Django settings for clog project.

Generated by 'django-admin startproject' using Django 1.8.14.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

import logging
import sys

import os
import warnings

reload(sys)
sys.setdefaultencoding('utf8')


try:
    from config.base_settings import *  # noqa
except ImportError:
    logging.warning("No clog_settings file found.")

# $DJANGO_ENVIRONMENT is set
ENVIRONMENT = os.getenv("DJANGO_ENVIRONMENT", "prod")
try:
    import_string = "from config.%s_settings import * " % ENVIRONMENT  # noqa
    exec import_string
except ImportError:
    logging.warning("No %s_settings file found." % ENVIRONMENT)

try:
    if ENVIRONMENT != 'test':
        from config.local_settings import *  # noqa
except ImportError:
    logging.warning("No local_settings file found.")


if not WEB_ROOT.endswith('/'):
    WEB_ROOT += '/'
# if LOGIN_URL is None:
#     LOGIN_URL = WEB_ROOT + 'auth/login/'
# if LOGOUT_URL is None:
#     LOGOUT_URL = WEB_ROOT + 'auth/logout/'
# if LOGIN_REDIRECT_URL is None:
#     LOGIN_REDIRECT_URL = WEB_ROOT

if STATIC_ROOT is None:
    STATIC_ROOT = os.path.abspath(os.path.join(ROOT_PATH, 'static'))

if STATIC_URL is None:
    STATIC_URL = WEB_ROOT + 'static/'


if not LOCAL_PATH:
    LOCAL_PATH = os.path.abspath(os.path.join(ROOT_PATH, 'local'))
    try:
        os.makedirs(LOCAL_PATH)
    except BaseException:
        pass

# Ensure that we always have a SECRET_KEY set, even when no local_settings.py
# file is present.
if not SECRET_KEY:
    from utils import secret_key

    SECRET_KEY = secret_key.generate_or_read_from_file(os.path.join(LOCAL_PATH, '.secret_key_store'))

if DEBUG:
    logging.basicConfig(level=logging.DEBUG)
